Fixes
jakub-bartoszek/Movie-browser pull request #19
Opened 2023-11-23 21:30 UTC by jakub-bartoszek-developer

I fixed a few responsive and logic troubles. Check it out 😸

2023-11-24 23:13 UTC, AndriiStafiniak commented
Wow, it looks great, much more professional now 🚀 Just one small thing to improve. I know it wasn't your task, but since you handle corrections, it would be fantastic if you could address it 😃We need to keep at least 2 columns on 320px wide screens. The problem is in the screenshots below
<img width="344" alt="Zrzut ekranu 2023-11-24 o 23 57 06" src="https://github.com/jakub-bartoszek-developer/Movie-browser/assets/131645596/6292fb7a-23e1-48cc-ad97-b05d40e50caa">
<img width="745" alt="Zrzut ekranu 2023-11-24 o 23 56 20" src="https://github.com/jakub-bartoszek-developer/Movie-browser/assets/131645596/655294c6-8e2d-4d5e-ba50-2f6524b68d03">
<img width="669" alt="Zrzut ekranu 2023-11-24 o 23 55 44" src="https://github.com/jakub-bartoszek-developer/Movie-browser/assets/131645596/ffb8d4b7-6f7a-4f4c-8654-0c47e579ed54">
<img width="350" alt="Zrzut ekranu 2023-11-24 o 23 54 39" src="https://github.com/jakub-bartoszek-developer/Movie-browser/assets/131645596/51da14ae-9dae-4195-a9d2-7e171a47de1f">

2023-11-25 01:22 UTC, AndriiStafiniak requested changes

2023-11-25 01:22 UTC, AndriiStafiniak commented on src/components/common/Tile/PersonTile/styled.jsx
>  `;
I think this change is causing problems
<img width="1034" alt="Zrzut ekranu 2023-11-25 o 02 17 09" src="https://github.com/jakub-bartoszek-developer/Movie-browser/assets/131645596/70d76cd9-6f50-40b5-a4cb-738c9fede260">

2023-11-25 01:47 UTC, AndriiStafiniak commented on src/components/common/Tile/Tile.jsx
> +					<ReleaseDate>{release_date.toString().replaceAll("-", ".")}</ReleaseDate>
It's great that you noticed it, but we also need to change the format. For example using release_date.toString().split("-").reverse().join(".")  I'll fix it, it's my mistake😃
<img width="288" alt="Zrzut ekranu 2023-11-25 o 02 42 06" src="https://github.com/jakub-bartoszek-developer/Movie-browser/assets/131645596/5c978180-c18f-4d2a-a480-53ce99d85f93">
<img width="424" alt="Zrzut ekranu 2023-11-25 o 02 42 19" src="https://github.com/jakub-bartoszek-developer/Movie-browser/assets/131645596/86fd090a-8919-4d61-b7ae-7a28d6743979">

2023-11-25 03:11 UTC, jakub-bartoszek-developer commented
Thanks for feedback, i will fix that!

2023-11-26 15:34 UTC, jakub-bartoszek-developer commented
I think it's working now!

2023-11-26 20:11 UTC, szymonbasiul commented
Good changes, its ok with me.

2023-11-26 20:19 UTC, szymonbasiul approved these changes
Its ok with me, good job ;)

2023-11-27 19:59 UTC, jakub-bartoszek commented
I think i will change a few more things!

2023-11-27 19:59 UTC, closed without merging