Z13/People
jakub-bartoszek/Movie-browser pull request #8
Opened 2023-11-14 20:53 UTC by szymonbasiul

Prepared people tiles, API implementation, searching feature. Small styling changes with image/name elements coming soon.

2023-11-18 18:33 UTC, AndriiStafiniak approved these changes
It looks great. Good job 😎 just a few small things to improve

2023-11-18 18:39 UTC, AndriiStafiniak commented
but this branch has  conflicts, how could you solve them and we can merge 😉

2023-11-18 19:04 UTC, AndriiStafiniak commented on src/components/common/Tile/PersonTile/PersonTile.jsx
> +      </Character>
here is a <p> element inside another <p> element. We can't do this. please correct it.

2023-11-19 17:01 UTC, jakub-bartoszek-developer requested changes
It is worth to add "status" of fetching people in your slice. When you do that, you can add conditional rendering of the People page like i did in Movies page. :)

2023-11-19 17:01 UTC, jakub-bartoszek commented on src/components/common/Tile/PersonTile/PersonTile.jsx
> +      </Character>
As Andrii said, you need to change that

2023-11-19 17:01 UTC, jakub-bartoszek commented on src/components/common/Tile/PersonTile/styled.jsx
If name of the person is too long, it doesnt look good. 
![image](https://github.com/jakub-bartoszek-developer/Movie-browser/assets/113419864/86ee896d-f006-4071-908a-83f9613a35ab)

2023-11-20 18:01 UTC, szymonbasiul commented on src/components/common/Tile/PersonTile/PersonTile.jsx
> +      </Character>
Thanks for feed. Updated

2023-11-20 19:08 UTC, szymonbasiul commented
Updates added.

2023-11-20 19:52 UTC, jakub-bartoszek-developer commented
Perfect!

2023-11-20 19:52 UTC, merged